import { Router } from "express";
import routerAuth from "./auth.router";
import routerCart from "./cart.router";
import routerCartItem from "./cartItem.router";
import routerCategory from "./category.router";
import routerCategoryType from "./categoryType.router";
import routerCoupon from "./coupon.router";
import routerOrder from "./order.router";
import routerOrderItem from "./orderItem.router";
import routerOrderStatus from "./orderStatus.router";
import routerPaymentMethod from "./paymentMethod.router";
import routerProduct from "./product.router";
import routerProductCategory from "./productCategory.router";
import routerProductOption from "./productOption.router";
import routerProductOptionValue from "./productOptionValue.router";
import routerProductUser from "./productUser.router";
import routerShipping from "./shipping.router";
import routerUser from "./user.router";
import routerVariant from "./variant.router";
import routerVariantValue from "./variantValue.router";
import routerUpload from "./upload.router";
import routerMeta from "./meta.router";
import routerBanner from "./banner.router";
const router = Router();

router.use("/auth", routerAuth);
router.use("/cart", routerCart);
router.use("/cart-item", routerCartItem);
router.use("/category", routerCategory);
router.use("/category-type", routerCategoryType);
router.use("/coupon", routerCoupon);
router.use("/order", routerOrder);
router.use("/order-item", routerOrderItem);
router.use("/order-status", routerOrderStatus);
router.use("/payment-method", routerPaymentMethod);
router.use("/product", routerProduct);
router.use("/product-category", routerProductCategory);
router.use("/product-option", routerProductOption);
router.use("/product-option-value", routerProductOptionValue);
router.use("/wishlist", routerProductUser);
router.use("/shipping", routerShipping);
router.use("/user", routerUser);
router.use("/variant", routerVariant);
router.use("/variant-value", routerVariantValue);
router.use("/upload", routerUpload);
router.use("/meta", routerMeta);
router.use("/banner", routerBanner);

export default router;
