export const DASHBOARD_LAYOUT = {
  SIDEBAR_WIDTH: 260,
  HEADER_HEIGHT: 60,
  CHART_MIDDLE_HEIGHT: 240,
  RECENT_ORDERS_HEIGHT: 380,
  NOTIFICATION_WIDTH: 280,
  BEST_SELLER_HEIGHT: 474,
  TABLE_LIST_HEIGHT: "calc(100vh - 77px)",
};

export const STATUS_CODE = {
  OK: 200,
  CREATED: 201,
};

export const API = {
  BASE_URL: "http://localhost:8080/",
};

export const TABLE = {
  CATEGORY_PAGE_SIZE: 10,
};
